buildscript {
    ext.kotlin_version = '1.9.20'
    apply from: '/Users/zhaozhenguo/Desktop/sourceCode/AndroidZex/config/versions.gradle'

    repositories {
        google()
        jcenter()
        mavenCentral()
        maven {
            url = uri("https://storage.googleapis.com/r8-releases/raw")
        }


    }
    dependencies {
        // classpath deps.greendao_plugin
        classpath('com.android.tools.build:gradle') {
            version {
                strictly '8.2.2'
            }
        }
//        classpath("com.android.tools:r8:8.9.35")

        //classpath deps.realm_plugin
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        //  maven { url 'https://maven.aliyun.com/repository/jcenter' }
        maven { url "https://jitpack.io" }
//        maven { url "https://search.maven.org/#search%7Cga%7C1%7Cio.sentry" }
        jcenter()
    }
}

task clean(type: Delete) {
    println '---------------执行删除操作build文件夹---------------'
    delete rootProject.buildDir
}

ext {//全局配置变量
    compileSdkVer = 34
    buildToolsVer = '34.0.0'
    minSdkVer = 26
    targetSdkVer = 34
    MiminSdkVer = 26
}
