package com.example.myappsecond.GreenDaos.Base;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.myappsecond.GreenDaos.Base.Cartoons;
import com.example.myappsecond.GreenDaos.Base.Character;
import com.example.myappsecond.GreenDaos.Base.User;

import com.example.myappsecond.GreenDaos.Base.CartoonsDao;
import com.example.myappsecond.GreenDaos.Base.CharacterDao;
import com.example.myappsecond.GreenDaos.Base.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cartoonsDaoConfig;
    private final DaoConfig characterDaoConfig;
    private final DaoConfig userDaoConfig;

    private final CartoonsDao cartoonsDao;
    private final CharacterDao characterDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cartoonsDaoConfig = daoConfigMap.get(CartoonsDao.class).clone();
        cartoonsDaoConfig.initIdentityScope(type);

        characterDaoConfig = daoConfigMap.get(CharacterDao.class).clone();
        characterDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        cartoonsDao = new CartoonsDao(cartoonsDaoConfig, this);
        characterDao = new CharacterDao(characterDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Cartoons.class, cartoonsDao);
        registerDao(Character.class, characterDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        cartoonsDaoConfig.clearIdentityScope();
        characterDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public CartoonsDao getCartoonsDao() {
        return cartoonsDao;
    }

    public CharacterDao getCharacterDao() {
        return characterDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
