//package com.rye.catcher.GreenDaos.Base;
//
//import java.util.Map;
//
//import org.greenrobot.greendao.AbstractDao;
//import org.greenrobot.greendao.AbstractDaoSession;
//import org.greenrobot.greendao.database.Database;
//import org.greenrobot.greendao.identityscope.IdentityScopeType;
//import org.greenrobot.greendao.internal.DaoConfig;
//
//import com.rye.catcher.GreenDaos.Base.TB_Cartoons;
//import com.rye.catcher.GreenDaos.Base.TB_User;
//import com.rye.catcher.GreenDaos.Base.TB_KeyValue;
//import com.rye.catcher.GreenDaos.Base.TB_Character;
//
//import com.rye.catcher.GreenDaos.Base.TB_CartoonsDao;
//import com.rye.catcher.GreenDaos.Base.TB_UserDao;
//import com.rye.catcher.GreenDaos.Base.TB_KeyValueDao;
//import com.rye.catcher.GreenDaos.Base.TB_CharacterDao;
//
//// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
//
///**
// * {@inheritDoc}
// *
// * @see org.greenrobot.greendao.AbstractDaoSession
// */
//public class DaoSession extends AbstractDaoSession {
//
//    private final DaoConfig tB_CartoonsDaoConfig;
//    private final DaoConfig tB_UserDaoConfig;
//    private final DaoConfig tB_KeyValueDaoConfig;
//    private final DaoConfig tB_CharacterDaoConfig;
//
//    private final TB_CartoonsDao tB_CartoonsDao;
//    private final TB_UserDao tB_UserDao;
//    private final TB_KeyValueDao tB_KeyValueDao;
//    private final TB_CharacterDao tB_CharacterDao;
//
//    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
//            daoConfigMap) {
//        super(db);
//
//        tB_CartoonsDaoConfig = daoConfigMap.get(TB_CartoonsDao.class).clone();
//        tB_CartoonsDaoConfig.initIdentityScope(type);
//
//        tB_UserDaoConfig = daoConfigMap.get(TB_UserDao.class).clone();
//        tB_UserDaoConfig.initIdentityScope(type);
//
//        tB_KeyValueDaoConfig = daoConfigMap.get(TB_KeyValueDao.class).clone();
//        tB_KeyValueDaoConfig.initIdentityScope(type);
//
//        tB_CharacterDaoConfig = daoConfigMap.get(TB_CharacterDao.class).clone();
//        tB_CharacterDaoConfig.initIdentityScope(type);
//
//        tB_CartoonsDao = new TB_CartoonsDao(tB_CartoonsDaoConfig, this);
//        tB_UserDao = new TB_UserDao(tB_UserDaoConfig, this);
//        tB_KeyValueDao = new TB_KeyValueDao(tB_KeyValueDaoConfig, this);
//        tB_CharacterDao = new TB_CharacterDao(tB_CharacterDaoConfig, this);
//
//        registerDao(TB_Cartoons.class, tB_CartoonsDao);
//        registerDao(TB_User.class, tB_UserDao);
//        registerDao(TB_KeyValue.class, tB_KeyValueDao);
//        registerDao(TB_Character.class, tB_CharacterDao);
//    }
//
//    public void clear() {
//        tB_CartoonsDaoConfig.clearIdentityScope();
//        tB_UserDaoConfig.clearIdentityScope();
//        tB_KeyValueDaoConfig.clearIdentityScope();
//        tB_CharacterDaoConfig.clearIdentityScope();
//    }
//
//    public TB_CartoonsDao getTB_CartoonsDao() {
//        return tB_CartoonsDao;
//    }
//
//    public TB_UserDao getTB_UserDao() {
//        return tB_UserDao;
//    }
//
//    public TB_KeyValueDao getTB_KeyValueDao() {
//        return tB_KeyValueDao;
//    }
//
//    public TB_CharacterDao getTB_CharacterDao() {
//        return tB_CharacterDao;
//    }
//
//}
